version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: school-registry-frontend
    ports:
      - "8090:80"
    restart: unless-stopped